name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-python-conda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: dronerl-env-v3
        environment-file: environment.yml
        auto-activate-base: false

    - name: Run Tests
      shell: bash -l {0}
      run: |
        conda activate dronerl-env-v3
        pytest tests/torch_tests

  test-python-pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt

    - name: Run Tests
      run: pytest tests/torch_tests

  test-jax-pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r jax_impl/requirements.cpu.txt

    - name: Run Tests
      run: pytest tests/jax_tests

  test-common-pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt
        pip install -r jax_impl/requirements.cpu.txt

    - name: Run Tests
      run: pytest tests/test_*.py
